/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:279ba6bb-7ce7-4505-a39e-9b6c951ad739",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yTEexc0yp",
    "aws_user_pools_web_client_id": "24i6c5a7m6106jhqt8jo1fo9pa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pfz4w6ievndb3kfjzfbqd4e5fu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r5xqdgqdcjf67e6eqoheg3zq4q"
};


export default awsmobile;
